name: Automation-Delta-Children Workflow
on:
 schedule:
    - cron: '0 11 * * 1-5'
jobs: 
  cypress-run:
    runs-on: ubuntu-latest, macos-latest
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://www.deltachildren.com/' # Waits for above
          browser: chrome
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        











          















