Cypress.on('uncaught:exception', () => { return false })

name: Display Cypress results
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/base:12.0.0-libgbm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        run: npm run cypress:run
      - name: Cypress report
        uses: cypress-io/github-action@v3
        with:
          commands: report
          build: 'Cypress info'
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/07-ci/*'
          reporter: mochawesome
          reporterOptions: '{"reportDir": "results"}'
          env:
  CYPRESS_ON_UNCAUGHT_EXCEPTION: |
    Cypress.on('uncaught:exception', () => {
      return false;
    })
  CYPRESS_APP_SCRIPT: |
    const style = document.createElement('style');
    style.innerHTML = `
      [data-hide-command-log-request] {
        display: none;
      }
    `;
    app.document.head.appendChild(style);

      
         


